language: ruby
rvm:
- 2.3.0
before_script:
- bundle exec rake db:create --all
- bundle exec rake db:migrate
script:
- bundle exec rake ci:tests
services:
- postgresql
deploy:
  provider: heroku
  api_key:
    secure: TC903iLgfaOtXXK/FfWRrRZRt2M2RE7IwU/Z3d+Sog1jPd8QXxjEMRDxEek6NjFkx38Y6ZRFCH3qg3Cyjz6VW9csnukGxNWc1rDCZT0+/NHV3XYqhlKnL4aqe1YCnJh2R7z09EiriATH99VU+QRdASIFTEdJBF//rql+WFQAcX+qATnA1RmmiuIWSJXjwG5vFhajzSjrfghXsdtrO6dJ9hlyRoFeLjaAuuXD/b/hMHB0N29Jh5B3zumGA+yqQakDFZ+loLW4u9Oygcwq2INlBNIpXQTtna6X+sOun5V0OpL9qU1QgkW9e5fMt8E/sEAKjnsx4bGSuojkMMRP/1jjjdX5FTuNmd/pXOPDSbfjXGw5/P1jXN+/PWulHhui7iiASz+lptGov2aKjK/aQ2GI357sn5pwZKpLMZijCurw5JDKOmCRO+an2urHlpdbhTIr4Py4KiU5RUV8cH66/CzKlJmBUcarnakncqL12ryTiY2FDh/XdaES9srO7HqTUd1s028sSAM2q7BsO13Wayvj8JLQbjZTpFvWJDZTJeo8pXXXFnFrZ/FXVXtBmuX30fpoU6jIv5zhLxFrX1YTTUAjQFChxnaUMFeDptCc7AYT5XfoNriDxQoLy/qE4uUq65jsKYW/SokP4c5ReOG0jALYOdXbi7z/B4WJ6tERTS0Sm9k=
  app: garden-club
  on:
    branch: dev
  run:
  - rake db:migrate
