# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00a9995db800bffb7fe4e92da501a5fd0d4ddd284838fb5467e508d572ef0054f0c270fb657c212867bba051a01fa2786dc41cf1449f5905e8c3aab516e2a36e

test:
  secret_key_base: f87b0d6d7cf5525e6cfe854fa1b3f8ca331c8e93e04e24f60461eb3e383042f3c7b54e5b5d064139a61fc9e6d68283321f5d6ffbd0a8e5c40ea3d413a3455c94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
